# k_performance.py

# bibliotecas gerais
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 

# config matplotlib
sns.set_style("ticks")
plt.rcParams['savefig.dpi'] = 200
plt.rcParams["figure.dpi"] = 100

plt.rcParams.update({
    "text.usetex": True,
    "font.family": "serif",
    "font.serif": ["Palatino"],
})

# importando os dados
mse_mlp_henon = pd.read_csv('results/mlp-basica/mlp-basica-henon.csv')
mse_mlp_logistic = pd.read_csv('results/mlp-basica/mlp-basica-logistic.csv')
mse_mlp_lorenz = pd.read_csv('results/mlp-basica/mlp-basica-lorenz.csv')
mse_mlp_mackeyglass = pd.read_csv('results/mlp-basica/mlp-basica-mackeyglass.csv')
mse_lstm_henon = pd.read_csv('results/lstm/lstm-henon.csv')
mse_lstm_logistic = pd.read_csv('results/lstm/lstm-logistic.csv')
mse_lstm_lorenz = pd.read_csv('results/lstm/lstm-lorenz.csv')
mse_lstm_mackeyglass = pd.read_csv('results/lstm/lstm-mackeyglass.csv')
mse_gru_henon = pd.read_csv('results/gru/gru-henon.csv')
mse_gru_logistic = pd.read_csv('results/gru/gru-logistic.csv')
mse_gru_lorenz = pd.read_csv('results/gru/gru-lorenz.csv')
mse_gru_mackeyglass = pd.read_csv('results/gru/gru-mackeyglass.csv')
mse_esn_henon = pd.read_csv('results/esn/esn-henon.csv')
mse_esn_logistic = pd.read_csv('results/esn/esn-logistic.csv')
mse_esn_lorenz = pd.read_csv('results/esn/esn-lorenz.csv')
mse_esn_mackeyglass = pd.read_csv('results/esn/esn-mackeyglass.csv')

# gerando os graficos
# mlp
print("Gerando os gráficos para a MLP...")
fig, ax = plt.subplots(nrows=2, ncols=2, tight_layout=True, figsize=(12, 8))
# henon
K = pd.DataFrame(mse_mlp_henon, columns=['K']).to_numpy()
K = K.ravel()
MSE = pd.DataFrame(mse_mlp_henon, columns=['Media do MSE']).to_numpy()
MSE = MSE.ravel()
MSE_std = pd.DataFrame(mse_mlp_henon, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std = MSE_std.ravel()
ax[0,0].errorbar(K, MSE, MSE_std, linestyle='None', marker='x', color='DarkGreen', label='MSE')
ax[0,0].set_xlabel('$K$')
ax[0,0].set_ylabel('Erro Quadrático Médio')
ax[0,0].set_title('Mapa de Hénon')
ax[0,0].grid()
# logistico
K = pd.DataFrame(mse_mlp_logistic, columns=['K']).to_numpy()
K = K.ravel()
MSE = pd.DataFrame(mse_mlp_logistic, columns=['Media do MSE']).to_numpy()
MSE = MSE.ravel()
MSE_std = pd.DataFrame(mse_mlp_logistic, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std = MSE_std.ravel()
ax[0,1].errorbar(K, MSE, MSE_std, linestyle='None', marker='x', color='Crimson', label='MSE')
ax[0,1].set_xlabel('$K$')
ax[0,1].set_ylabel('Erro Quadrático Médio')
ax[0,1].set_title('Mapa logístico')
ax[0,1].grid()
# lorenz
K = pd.DataFrame(mse_mlp_lorenz, columns=['K']).to_numpy()
K = K.ravel()
MSE = pd.DataFrame(mse_mlp_lorenz, columns=['Media do MSE']).to_numpy()
MSE = MSE.ravel()
MSE_std = pd.DataFrame(mse_mlp_lorenz, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std = MSE_std.ravel()
ax[1,0].errorbar(K, MSE, MSE_std, linestyle='None', marker='x', color='DarkBlue', label='MSE')
ax[1,0].set_xlabel('$K$')
ax[1,0].set_ylabel('Erro Quadrático Médio')
ax[1,0].set_title('Sistema de Lorenz')
ax[1,0].grid()
# mackeyglass
K = pd.DataFrame(mse_mlp_mackeyglass, columns=['K']).to_numpy()
K = K.ravel()
MSE = pd.DataFrame(mse_mlp_mackeyglass, columns=['Media do MSE']).to_numpy()
MSE = MSE.ravel()
MSE_std = pd.DataFrame(mse_mlp_mackeyglass, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std = MSE_std.ravel()
ax[1,1].errorbar(K, MSE, MSE_std, linestyle='None', marker='x', color='DarkOrange', label='MSE')
ax[1,1].set_xlabel('$K$')
ax[1,1].set_ylabel('Erro Quadrático Médio')
ax[1,1].set_title('Equações de Mackey-Glass')
ax[1,1].grid()
fig.suptitle("Progressão do EQM com o valor de $K$ para a MLP nos cenários avaliados")
sns.despine()
fig.savefig("images/results/mlp-mse.pdf")

print("Gerando os gráficos para a LSTM...")
# lstm
fig, ax = plt.subplots(nrows=2, ncols=2, tight_layout=True, figsize=(12, 8))
# henon
K = pd.DataFrame(mse_lstm_henon, columns=['K']).to_numpy()
K = K.ravel()
MSE = pd.DataFrame(mse_lstm_henon, columns=['Media do MSE']).to_numpy()
MSE = MSE.ravel()
MSE_std = pd.DataFrame(mse_lstm_henon, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std = MSE_std.ravel()
ax[0,0].errorbar(K, MSE, MSE_std, linestyle='None', marker='d', color='DarkGreen', label='MSE')
ax[0,0].set_xlabel('$K$')
ax[0,0].set_ylabel('Erro Quadrático Médio')
ax[0,0].set_title('Mapa de Hénon')
ax[0,0].grid()
# logistico
K = pd.DataFrame(mse_lstm_logistic, columns=['K']).to_numpy()
K = K.ravel()
MSE = pd.DataFrame(mse_lstm_logistic, columns=['Media do MSE']).to_numpy()
MSE = MSE.ravel()
MSE_std = pd.DataFrame(mse_lstm_logistic, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std = MSE_std.ravel()
ax[0,1].errorbar(K, MSE, MSE_std, linestyle='None', marker='d', color='Crimson', label='MSE')
ax[0,1].set_xlabel('$K$')
ax[0,1].set_ylabel('Erro Quadrático Médio')
ax[0,1].set_title('Mapa logístico')
ax[0,1].grid()
# lorenz
K = pd.DataFrame(mse_lstm_lorenz, columns=['K']).to_numpy()
K = K.ravel()
MSE = pd.DataFrame(mse_lstm_lorenz, columns=['Media do MSE']).to_numpy()
MSE = MSE.ravel()
MSE_std = pd.DataFrame(mse_lstm_lorenz, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std = MSE_std.ravel()
ax[1,0].errorbar(K, MSE, MSE_std, linestyle='None', marker='d', color='DarkBlue', label='MSE')
ax[1,0].set_xlabel('$K$')
ax[1,0].set_ylabel('Erro Quadrático Médio')
ax[1,0].set_title('Sistema de Lorenz')
ax[1,0].grid()
# mackeyglass
K = pd.DataFrame(mse_lstm_mackeyglass, columns=['K']).to_numpy()
K = K.ravel()
MSE = pd.DataFrame(mse_lstm_mackeyglass, columns=['Media do MSE']).to_numpy()
MSE = MSE.ravel()
MSE_std = pd.DataFrame(mse_lstm_mackeyglass, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std = MSE_std.ravel()
ax[1,1].errorbar(K, MSE, MSE_std, linestyle='None', marker='d', color='DarkOrange', label='MSE')
ax[1,1].set_xlabel('$K$')
ax[1,1].set_ylabel('Erro Quadrático Médio')
ax[1,1].set_title('Equações de Mackey-Glass')
ax[1,1].grid()
fig.suptitle("Progressão do EQM com o valor de $K$ para a LSTM nos cenários avaliados")
sns.despine()
fig.savefig("images/results/lstm-mse.pdf")

print("Gerando os gráficos para a GRU...")
# gru 
fig, ax = plt.subplots(nrows=2, ncols=2, tight_layout=True, figsize=(12, 8))
# henon
K = pd.DataFrame(mse_gru_henon, columns=['K']).to_numpy()
K = K.ravel()
MSE = pd.DataFrame(mse_gru_henon, columns=['Media do MSE']).to_numpy()
MSE = MSE.ravel()
MSE_std = pd.DataFrame(mse_gru_henon, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std = MSE_std.ravel()
ax[0,0].errorbar(K, MSE, MSE_std, linestyle='None', marker='H', color='DarkGreen', label='MSE')
ax[0,0].set_xlabel('$K$')
ax[0,0].set_ylabel('Erro Quadrático Médio')
ax[0,0].set_title('Mapa de Hénon')
ax[0,0].grid()
# logistico
K = pd.DataFrame(mse_gru_logistic, columns=['K']).to_numpy()
K = K.ravel()
MSE = pd.DataFrame(mse_gru_logistic, columns=['Media do MSE']).to_numpy()
MSE = MSE.ravel()
MSE_std = pd.DataFrame(mse_gru_logistic, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std = MSE_std.ravel()
ax[0,1].errorbar(K, MSE, MSE_std, linestyle='None', marker='H', color='Crimson', label='MSE')
ax[0,1].set_xlabel('$K$')
ax[0,1].set_ylabel('Erro Quadrático Médio')
ax[0,1].set_title('Mapa logístico')
ax[0,1].grid()
# lorenz
K = pd.DataFrame(mse_gru_lorenz, columns=['K']).to_numpy()
K = K.ravel()
MSE = pd.DataFrame(mse_gru_lorenz, columns=['Media do MSE']).to_numpy()
MSE = MSE.ravel()
MSE_std = pd.DataFrame(mse_gru_lorenz, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std = MSE_std.ravel()
ax[1,0].errorbar(K, MSE, MSE_std, linestyle='None', marker='H', color='DarkBlue', label='MSE')
ax[1,0].set_xlabel('$K$')
ax[1,0].set_ylabel('Erro Quadrático Médio')
ax[1,0].set_title('Sistema de Lorenz')
ax[1,0].grid()
# mackeyglass
K = pd.DataFrame(mse_gru_mackeyglass, columns=['K']).to_numpy()
K = K.ravel()
MSE = pd.DataFrame(mse_gru_mackeyglass, columns=['Media do MSE']).to_numpy()
MSE = MSE.ravel()
MSE_std = pd.DataFrame(mse_gru_mackeyglass, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std = MSE_std.ravel()
ax[1,1].errorbar(K, MSE, MSE_std, linestyle='None', marker='H', color='DarkOrange', label='MSE')
ax[1,1].set_xlabel('$K$')
ax[1,1].set_ylabel('Erro Quadrático Médio')
ax[1,1].set_title('Equações de Mackey-Glass')
ax[1,1].grid()
fig.suptitle("Progressão do EQM com o valor de $K$ para a GRU nos cenários avaliados")
sns.despine()
fig.savefig("images/results/gru-mse.pdf")

# esn
print("Gerando os gráficos para a ESN...")
fig, ax = plt.subplots(nrows=2, ncols=2, tight_layout=True, figsize=(12, 8))
# henon
K = pd.DataFrame(mse_esn_henon, columns=['K']).to_numpy()
K = K.ravel()
MSE = pd.DataFrame(mse_esn_henon, columns=['Media do MSE']).to_numpy()
MSE = MSE.ravel()
MSE_std = pd.DataFrame(mse_esn_henon, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std = MSE_std.ravel()
ax[0,0].errorbar(K, MSE, MSE_std, linestyle='None', marker='*', color='DarkGreen', label='MSE')
ax[0,0].set_xlabel('$K$')
ax[0,0].set_ylabel('Erro Quadrático Médio')
ax[0,0].set_title('Mapa de Hénon')
ax[0,0].grid()
# logistico
K = pd.DataFrame(mse_esn_logistic, columns=['K']).to_numpy()
K = K.ravel()
MSE = pd.DataFrame(mse_esn_logistic, columns=['Media do MSE']).to_numpy()
MSE = MSE.ravel()
MSE_std = pd.DataFrame(mse_esn_logistic, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std = MSE_std.ravel()
ax[0,1].errorbar(K, MSE, MSE_std, linestyle='None', marker='*', color='Crimson', label='MSE')
ax[0,1].set_xlabel('$K$')
ax[0,1].set_ylabel('Erro Quadrático Médio')
ax[0,1].set_title('Mapa logístico')
ax[0,1].grid()
# lorenz
K = pd.DataFrame(mse_esn_lorenz, columns=['K']).to_numpy()
K = K.ravel()
MSE = pd.DataFrame(mse_esn_lorenz, columns=['Media do MSE']).to_numpy()
MSE = MSE.ravel()
MSE_std = pd.DataFrame(mse_esn_lorenz, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std = MSE_std.ravel()
ax[1,0].errorbar(K, MSE, MSE_std, linestyle='None', marker='*', color='DarkBlue', label='MSE')
ax[1,0].set_xlabel('$K$')
ax[1,0].set_ylabel('Erro Quadrático Médio')
ax[1,0].set_title('Sistema de Lorenz')
ax[1,0].grid()
# mackeyglass
K = pd.DataFrame(mse_esn_mackeyglass, columns=['K']).to_numpy()
K = K.ravel()
MSE = pd.DataFrame(mse_esn_mackeyglass, columns=['Media do MSE']).to_numpy()
MSE = MSE.ravel()
MSE_std = pd.DataFrame(mse_esn_mackeyglass, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std = MSE_std.ravel()
ax[1,1].errorbar(K, MSE, MSE_std, linestyle='None', marker='*', color='DarkOrange', label='MSE')
ax[1,1].set_xlabel('$K$')
ax[1,1].set_ylabel('Erro Quadrático Médio')
ax[1,1].set_title('Equações de Mackey-Glass')
ax[1,1].grid()
#fig.suptitle("Progressão do EQM com o valor de $K$ para a ESN nos cenários avaliados")
sns.despine()
fig.savefig("images/results/esn-mse.pdf")

# comparacao entre modelos
print("Gerando as comparações entre os modelos...")
# henon
fig, ax = plt.subplots(tight_layout=True)
K = pd.DataFrame(mse_mlp_henon, columns=['K']).to_numpy()
K = K.ravel()
MSE_mlp = pd.DataFrame(mse_mlp_henon, columns=['Media do MSE']).to_numpy()
MSE_mlp = MSE_mlp.ravel()
MSE_std_mlp = pd.DataFrame(mse_mlp_henon, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std_mlp = MSE_std_mlp.ravel()
MSE_lstm = pd.DataFrame(mse_lstm_henon, columns=['Media do MSE']).to_numpy()
MSE_lstm = MSE_lstm.ravel()
MSE_std_lstm = pd.DataFrame(mse_lstm_henon, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std_lstm = MSE_std_lstm.ravel()
MSE_gru = pd.DataFrame(mse_gru_henon, columns=['Media do MSE']).to_numpy()
MSE_gru = MSE_gru.ravel()
MSE_std_gru = pd.DataFrame(mse_gru_henon, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std_gru = MSE_std_gru.ravel()
MSE_esn = pd.DataFrame(mse_esn_henon, columns=['Media do MSE']).to_numpy()
MSE_esn = MSE_esn.ravel()
MSE_std_esn = pd.DataFrame(mse_esn_henon, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std_esn = MSE_std_esn.ravel()
ax.errorbar(K, MSE_mlp, MSE_std_mlp, linestyle='None', marker='x', label='MLP')
ax.errorbar(K, MSE_lstm, MSE_std_lstm, linestyle='None', marker='d', label='LSTM')
ax.errorbar(K, MSE_gru, MSE_std_gru, linestyle='None', marker='H', label='GRU')
ax.errorbar(K, MSE_esn, MSE_std_esn, linestyle='None', marker='*', label='ESN')
ax.legend()
ax.set_xlabel('$K$')
ax.set_ylabel('Erro Quadrático Médio')
ax.set_title('Desempenho no mapa de Hénon para as redes analisadas')
sns.despine()
ax.grid()
fig.savefig("images/results/henon.pdf")

# logistic
fig, ax = plt.subplots(tight_layout=True)
K = pd.DataFrame(mse_mlp_logistic, columns=['K']).to_numpy()
K = K.ravel()
MSE_mlp = pd.DataFrame(mse_mlp_logistic, columns=['Media do MSE']).to_numpy()
MSE_mlp = MSE_mlp.ravel()
MSE_std_mlp = pd.DataFrame(mse_mlp_logistic, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std_mlp = MSE_std_mlp.ravel()
MSE_lstm = pd.DataFrame(mse_lstm_logistic, columns=['Media do MSE']).to_numpy()
MSE_lstm = MSE_lstm.ravel()
MSE_std_lstm = pd.DataFrame(mse_lstm_logistic, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std_lstm = MSE_std_lstm.ravel()
MSE_gru = pd.DataFrame(mse_gru_logistic, columns=['Media do MSE']).to_numpy()
MSE_gru = MSE_gru.ravel()
MSE_std_gru = pd.DataFrame(mse_gru_logistic, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std_gru = MSE_std_gru.ravel()
MSE_esn = pd.DataFrame(mse_esn_logistic, columns=['Media do MSE']).to_numpy()
MSE_esn = MSE_esn.ravel()
MSE_std_esn = pd.DataFrame(mse_esn_logistic, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std_esn = MSE_std_esn.ravel()
ax.errorbar(K, MSE_mlp, MSE_std_mlp, linestyle='None', marker='x', label='MLP')
ax.errorbar(K, MSE_lstm, MSE_std_lstm, linestyle='None', marker='d', label='LSTM')
ax.errorbar(K, MSE_gru, MSE_std_gru, linestyle='None', marker='H', label='GRU')
ax.errorbar(K, MSE_esn, MSE_std_esn, linestyle='None', marker='*', label='ESN')
ax.legend()
ax.set_xlabel('$K$')
ax.set_ylabel('Erro Quadrático Médio')
ax.set_title('Desempenho no mapa logístico para as redes analisadas')
sns.despine()
ax.grid()
fig.savefig("images/results/logistic.pdf")

# sistema de lorenz
fig, ax = plt.subplots(tight_layout=True)
K = pd.DataFrame(mse_mlp_lorenz, columns=['K']).to_numpy()
K = K.ravel()
MSE_mlp = pd.DataFrame(mse_mlp_lorenz, columns=['Media do MSE']).to_numpy()
MSE_mlp = MSE_mlp.ravel()
MSE_std_mlp = pd.DataFrame(mse_mlp_lorenz, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std_mlp = MSE_std_mlp.ravel()
MSE_lstm = pd.DataFrame(mse_lstm_lorenz, columns=['Media do MSE']).to_numpy()
MSE_lstm = MSE_lstm.ravel()
MSE_std_lstm = pd.DataFrame(mse_lstm_lorenz, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std_lstm = MSE_std_lstm.ravel()
MSE_gru = pd.DataFrame(mse_gru_lorenz, columns=['Media do MSE']).to_numpy()
MSE_gru = MSE_gru.ravel()
MSE_std_gru = pd.DataFrame(mse_gru_lorenz, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std_gru = MSE_std_gru.ravel()
MSE_esn = pd.DataFrame(mse_esn_lorenz, columns=['Media do MSE']).to_numpy()
MSE_esn = MSE_esn.ravel()
MSE_std_esn = pd.DataFrame(mse_esn_lorenz, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std_esn = MSE_std_esn.ravel()
ax.errorbar(K, MSE_mlp, MSE_std_mlp, linestyle='None', marker='x', label='MLP')
ax.errorbar(K, MSE_lstm, MSE_std_lstm, linestyle='None', marker='d', label='LSTM')
ax.errorbar(K, MSE_gru, MSE_std_gru, linestyle='None', marker='H', label='GRU')
ax.errorbar(K, MSE_esn, MSE_std_esn, linestyle='None', marker='*', label='ESN')
ax.legend()
ax.set_xlabel('$K$')
ax.set_ylabel('Erro Quadrático Médio')
ax.set_title('Desempenho no sistema de Lorenz para as redes analisadas')
sns.despine()
ax.grid()
fig.savefig("images/results/lorenz.pdf")

# mackey-glass
fig, ax = plt.subplots(tight_layout=True)
K = pd.DataFrame(mse_mlp_mackeyglass, columns=['K']).to_numpy()
K = K.ravel()
MSE_mlp = pd.DataFrame(mse_mlp_mackeyglass, columns=['Media do MSE']).to_numpy()
MSE_mlp = MSE_mlp.ravel()
MSE_std_mlp = pd.DataFrame(mse_mlp_mackeyglass, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std_mlp = MSE_std_mlp.ravel()
MSE_lstm = pd.DataFrame(mse_lstm_mackeyglass, columns=['Media do MSE']).to_numpy()
MSE_lstm = MSE_lstm.ravel()
MSE_std_lstm = pd.DataFrame(mse_lstm_mackeyglass, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std_lstm = MSE_std_lstm.ravel()
MSE_gru = pd.DataFrame(mse_gru_mackeyglass, columns=['Media do MSE']).to_numpy()
MSE_gru = MSE_gru.ravel()
MSE_std_gru = pd.DataFrame(mse_gru_mackeyglass, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std_gru = MSE_std_gru.ravel()
MSE_esn = pd.DataFrame(mse_esn_mackeyglass, columns=['Media do MSE']).to_numpy()
MSE_esn = MSE_esn.ravel()
MSE_std_esn = pd.DataFrame(mse_esn_mackeyglass, columns=['Desvio Padrao do MSE']).to_numpy()
MSE_std_esn = MSE_std_esn.ravel()
ax.errorbar(K, MSE_mlp, MSE_std_mlp, linestyle='None', marker='x', label='MLP')
ax.errorbar(K, MSE_lstm, MSE_std_lstm, linestyle='None', marker='d', label='LSTM')
ax.errorbar(K, MSE_gru, MSE_std_gru, linestyle='None', marker='H', label='GRU')
ax.errorbar(K, MSE_esn, MSE_std_esn, linestyle='None', marker='*', label='ESN')
ax.legend()
ax.set_xlabel('$K$')
ax.set_ylabel('Erro Quadrático Médio')
ax.set_title('Desempenho na equações de Mackey-Glass para as redes analisadas')
sns.despine()
ax.grid()
fig.savefig("images/results/mackeyglass.pdf")
print("Gráficos gerados!")